### ISSUE TITLE
Memory allocation and SCONE error while running benchmark on csv-to-run.py

### ISSUE THREAD

**Issue by shawnk04** [cssl-unist/tweezer#3]
Hi, I'm trying to run the benchmarks via /test/csv-to-run.py, however I am running into an error for each benchmark.

A benchmark will run for a few seconds, throw a few SCONE warnings, then throw these two errors, causing that benchmark to cut short and move onto the next:
`src/page_heap_allocator.h:74] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 131072 48`
`[SCONE|ERROR] tools/starter/signal.c:61:die_by_signal(): Enclave terminated due to signal: Aborted`

These errors repeat for all benchmarks as well. I've attached the full console log [here](https://github.com/cssl-unist/tweezer/files/9096164/console.txt) in case it's needed. Any help is greatly appreciated!

**Comment by zktsd813** [comment]
Hi.
It seems that memory for EPC is full.
You can fix it by increasing SCONE_HEAP in /test/csv_to_run.py(line 35).

However, note that increasing SCONE_HEAP will increasing reserved memory for EPC which means unsecure memory space for your application will decrease. 
You have to find sweet spot for SCONE_HEAP that your application's unsecure memory will not touch swap memory which will degrade performance.

The reason of this problem is that the memory required for benchmark is huge regardless of its memory working set which nearly fitted into EPC limitation in tweezer case.

**Comment by shawnk04** [comment]
I've went ahead and modified the SCONE_HEAP variable a bit more and still am receiving errors.

At values 46 and below, I receive that error in my first post. From 47 to 63, I receive this new error:
`[SCONE|ERROR] tools/libsgx/src/builder.c:481:add_page_oot(): failed to add page to enclave: Cannot allocate memory`
`[SCONE|FATAL] tools/starter/main.c:560:enclave_create(): Could not create enclave: Error`

Here's the full [log](https://github.com/cssl-unist/tweezer/files/9151919/log.txt) if it helps.

What value for SCONE_HEAP did you use in your Tweezer research paper? At the moment, I am simply trying to rerun your experiments in as similar an environment as possible.

Here are my hardware specs:
- PowerEdge T130 with a 4-core 3.00 GHz Intel Xeon E3-1220 v6 CPU
- System runs 64-bit Ubuntu 18.04.6 with Linux kernel version 4.19.99 
- Boot with the root file system on a 500 GB TOSHIBA DT01ACA0 HDD
- The SSD under test is a 250 GB Samsung EVO 860 SSD with a 512-byte page size and 12 GB write cache
- Also, I would like to add that I noticed my machine has only 32 GB RAM and you used 64, so I upgraded my machine to 64 GB to match

Do you see any hardware differences that could be causing errors?

**Comment by zktsd813** [comment]
we tested our system with 16G.

And root cause of your problem may not be shortage of EPC region. 
Because /app directory where generated temfs resides located in privileged region.
In the log, I found that fallocate were not function correctly.
This region is for our untrusted memory region. (/app/untrustedmemory ) 
Could you try again with 'sudo' permission ?

Edit : I also update generate_tmpfs.sh 
Could you delete /app directory and try again?
You should check that /app is backed by tmpfs (using 'df' command).
/app/untrusted_memory(file that were used as untrusted memory) will be generated during experiments.

**Comment by shawnk04** [comment]
Using 16G gives the error in my original post. And using sudo seemed to have helped with the issue with fallocate not running properly. However, the same error messages as earlier still persist.

I also deleted /app and tried again and saw that it's backed by tmpfs: 
`tmpfs                             8388608       0   8388608   0% /app/untrusted_memory`

Again this still hasn't helped with the errors sadly. Any further help is greatly appreciated.

**Comment by zktsd813** [comment]
Sorry for delay.

'untrusted_memory' should be a dummy file, not a directory.
`tmpfs                                8388608   8388608          0 100% /app`

Could you try again?

**Comment by shawnk04** [comment]
No worries. I went ahead and pulled the repo and reran everything. It appears to have ran for a bit (progress!) but ended up with a missing file error:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/69802050/185168784-5055124c-d19f-4d0a-ac06-2f76cf4812e9.png">

I believe it is missing a script to create the output file?

**Comment by zktsd813** [comment]
Yes. It seems that "output" directory was missing.
You can try with test script after generating "output" directory so that benchmark results can be stored in "output" directory.
