### ISSUE TITLE
build error and test failure

### ISSUE THREAD

**Issue by jyizheng** [cssl-unist/tweezer#6]
<img width="1543" alt="Screenshot 2022-11-18 at 7 09 54 PM" src="https://user-images.githubusercontent.com/2645726/202831601-967d7dcb-463b-43a3-adcb-73bd8764dc05.png">

I got the error in the above screenshot when running "docker build -t tweezer:0.0 ./". Is this a serious problem, though the screenshot shows the container was successfully built? 

However, I cannot run "python3 csv-to-run.py" afterward. The error message is below. I wonder if the above build process problem causes the error. Thank you very much for your feedback.

<img width="1544" alt="Screenshot 2022-11-18 at 7 19 34 PM" src="https://user-images.githubusercontent.com/2645726/202832065-cbe9e510-4e42-450b-8485-9745be545854.png">

**Comment by hyungon-moon** [comment]
It is hard to tell what exactly is the problem from the log because it does not match any problem we have faced before.

I think you should first try to fix the first problem which seems to be from building the tcmalloc, Tweezer's untrusted memory allocator.

Given that the problem in the second error log is SIGILL, it is likely that the image built for Enclave has not been built successfully.
